--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/crnw-dev/LockPlayerPM
build-by-default: true
branches:
- master
projects:
  LockPlayerPM:
    path: LockPlayerPM/
    model: virion
    type: library
...
